TeraFrontendMVC/Controllers/ResultsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Globalization;
using System.Text.Json;
using TeraFrontendMVC.Models;
using TeraFrontendMVC.Models.Region;
using TeraFrontendMVC.Models.Results;

namespace TeraFrontendMVC.Controllers
{
    public class ResultsController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly ILogger<ResultsController> _logger;
        private readonly ApiUrls _apiUrls;

        public ResultsController(HttpClient httpClient, ILogger<ResultsController> logger, IOptions<ApiUrls> apiUrls)
        {
            _httpClient = httpClient;
            _logger = logger;
            _apiUrls = apiUrls.Value;
        }

        // GET: Results
        public async Task<IActionResult> Index()
        {
            // Obtener los estados, municipios y parroquias reutilizando los métodos privados
            var states = await GetStates(null);
            var municipalities = new List<MunicipalityViewModel>();
            var parishes = new List<ParishViewModel>();

            // Crear un modelo para pasar a la vista
            var model = new SelectsViewModel
            {
                States = states,
                Municipalities = municipalities,
                Parishes = parishes
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Buscar(int? codEdo, int? munId, int? codPar, int? pageSize, int? pageNumber)
        {

            try
            {
                var token = HttpContext.Session.GetString("AuthToken");

                string url = $"{_apiUrls.Resultados}/resultados?codEdo={codEdo}&munId={munId}&codPar={codPar}&pageSize={pageSize}&pageNumber={pageNumber}";

                using (HttpClient client = new HttpClient())
                {

                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                    var response = await client.GetAsync(url);

                    if (response.IsSuccessStatusCode)
                    {
                        var jsonData = await response.Content.ReadAsStringAsync();

                        // Deserializar la respuesta JSON en el modelo ResultadosResponse
                        var resultadosResponse = JsonConvert.DeserializeObject<ResultsResponseViewModel>(jsonData);

                        if (resultadosResponse != null)
                        {
                            resultadosResponse.PageNumber = pageNumber?.ToString() ?? "1";
                            return PartialView("_ResultsPartial", resultadosResponse);
                        }
                        else
                        {
                            _logger.LogError("La respuesta JSON es nula o no tiene el formato esperado.");
                            ViewBag.ErrorMessage = "Ocurrió un error al obtener los resultados. Por favor, verifica tu selección e intenta nuevamente.";
                            return PartialView("_ResultsPartial");
                        }
                    }
                    else
                    {
                        _logger.LogError("Error al buscar los resultados: " + response.StatusCode);
                        ViewBag.ErrorMessage = "Ocurrió un error al obtener los resultados. Por favor, verifica tu selección e intenta nuevamente.";
                        return PartialView("_ResultsPartial");
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Excepción al buscar los resultados.");
                ViewBag.ErrorMessage = "Ocurrió un error al obtener los resultados. Por favor, verifica tu selección e intenta nuevamente.";
                return PartialView("_ResultsPartial");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetMunicipios(int codEdo)
        {
            var municipios = await GetMunicipality(null, codEdo); // Obtener municipios filtrados por estado
            return Json(municipios);
        }

        [HttpGet]
        public async Task<IActionResult> GetParroquias(int codMun)
        {
            var parroquias = await GetParish(codMun, null); // Obtener parroquias filtradas por municipio
            return Json(parroquias);
        }



        private async Task<List<StateViewModel>> GetStates(int? codEdo)
        {

            List<StateViewModel> states = new List<StateViewModel>();

            try
            {
                // Crear la query string condicionalmente según los parámetros
                var queryString = $"{_apiUrls.Region}/estados?";
                if (codEdo.HasValue)
                {
                    queryString += $"codEdo={codEdo.Value}";
                }

                // Eliminar el último '&' sobrante o '?'
                queryString = queryString.TrimEnd('&', '?');

                // Enviar authToken en el header
                var token = HttpContext.Session.GetString("AuthToken");
                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                var response = await _httpClient.GetAsync(queryString);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    states = System.Text.Json.JsonSerializer.Deserialize<List<StateViewModel>>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    // Aplicar el formato al nombre de cada estado
                    states.ForEach(state => state.Nombre = FormatName(state.Nombre));
                }
                else
                {
                    _logger.LogError("Error al obtener la lista de estados. Status Code: {StatusCode}", response.StatusCode);
                }
            }
            catch (Exception ex) {
                Console.WriteLine(ex.Message);
            }

            return states;
        }

        private async Task<List<MunicipalityViewModel>> GetMunicipality(int? codMun, int? codEdo)
        {

            List<MunicipalityViewModel> municipality = new List<MunicipalityViewModel>();

            try
            {
                // Crear la query string condicionalmente según los parámetros
                var queryString = $"{_apiUrls.Region}/municipios?";
                if (codMun.HasValue)
                {
                    queryString += $"codMun={codMun.Value}&";
                }
                if (codEdo.HasValue)
                {
                    queryString += $"codEdo={codEdo.Value}&";
                }

                // Eliminar el último '&' sobrante o '?'
                queryString = queryString.TrimEnd('&', '?');

                // Enviar authToken en el header
                var token = HttpContext.Session.GetString("AuthToken");
                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                // Realiza la solicitud al backend con los parámetros necesarios
                var response = await _httpClient.GetAsync(queryString);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    municipality = System.Text.Json.JsonSerializer.Deserialize<List<MunicipalityViewModel>>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    municipality.ForEach(mun => mun.Nombre = FormatName(mun.Nombre));
                }
                else
                {
                    _logger.LogError("Error al obtener la lista de municipios. Status Code: {StatusCode}", response.StatusCode);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return municipality;
        }

        private async Task<List<ParishViewModel>> GetParish(int? codMun, int? codPar)
        {

            List<ParishViewModel> parish = new List<ParishViewModel>();

            try
            {
                // Crear la query string condicionalmente según los parámetros
                var queryString = $"{_apiUrls.Region}/parroquias?";
                if (codMun.HasValue)
                {
                    queryString += $"codMun={codMun.Value}";
                }
                if (codPar.HasValue)
                {
                    Console.WriteLine("Entre al if");
                    queryString += $"codPar={codPar.Value}";
                }

                // Eliminar el último '&' sobrante o '?'
                queryString = queryString.TrimEnd('&', '?');

                // Enviar authToken en el header
                var token = HttpContext.Session.GetString("AuthToken");
                _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);

                // Realiza la solicitud al backend con los parámetros necesarios
                var response = await _httpClient.GetAsync(queryString);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    parish = System.Text.Json.JsonSerializer.Deserialize<List<ParishViewModel>>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    parish.ForEach(par => par.Nombre = FormatName(par.Nombre));
                }
                else
                {
                    _logger.LogError("Error al obtener la lista de municipios. Status Code: {StatusCode}", response.StatusCode);
                }
            }
            catch (Exception ex)
            {

TeraFrontendMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elecciones 2024</title>

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/images/winner.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TeraFrontendMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ResultsPartialCustomStyles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/SelectsPartialCustomStyles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/AccountViewCustomStyles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" asp-append-version="true">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand header-nav-a-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/elecciones-logo.png" alt="Elecciones 2024" class="navbar-brand-logo" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 me-auto">
                        <li style="margin-right: 10px">
                            <a class="header-nav-a-link" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (!string.IsNullOrEmpty(Context.Session.GetString("AuthToken")))
                        {
                            <li class="nav-item" style="margin-right: 10px">
                                <a class="header-nav-a-link" asp-area="" asp-controller="Results" asp-action="Index">Resultados</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav ms-auto">

                        @{
                            var token = Context.Session.GetString("AuthToken");
                            if (!string.IsNullOrEmpty(token))
                            {
                                <li class="nav-item dropdown">
                                    <button class="btn btn-secondary dropdown-toggle"
                                            type="button"
                                            id="settingsDropdown"
                                            data-bs-toggle="dropdown"
                                            aria-expanded="false">
                                        Configuración
                                    </button>
                                    <ul class="dropdown-menu dropdown-menu-end ul-menu-container" aria-labelledby="settingsDropdown">
                                        <li>
                                            <a asp-area="" asp-controller="Account" asp-action="UserProfile" class="dropdown-item">Perfil de Usuario</a>
                                        </li>
                                        <li>
                                            <a href="javascript:document.getElementById('logoutForm').submit();" class="dropdown-item">Cerrar Sesión</a>
                                        </li>
                                        <form id="logoutForm" asp-area="" asp-controller="Account" asp-action="Logout" method="post" style="display: none;"></form>
                                    </ul>
                                </li>

                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="header-nav-a-link" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                                </li>
                            }
                        }
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TeraFrontendMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/various-actions.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TeraFrontendMVC/Views/Shared/_ResultsPartial.cshtml
@using TeraFrontendMVC.Models.Results
@model ResultsResponseViewModel

<!-- Tabla de resultados -->
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger">
        @ViewBag.ErrorMessage
    </div>
}
else
{
    <div id="resultadosTableContainer">
        <table id="resultadosTable">
            <tr>
                <th>Centro</th>
                <th>Mesa</th>
                <th>EG</th>
                <th>NM</th>
                <th>LM</th>
                <th>JABE</th>
                <th>JOBR</th>
                <th>AE</th>
                <th>CF</th>
                <th>DC</th>
                <th>EM</th>
                <th>BERA</th>
            </tr>
            @if (@Model.Amount > 0)
            {
                @foreach (var resultado in Model.Resultados)
                {
                    <tr>
                        <td>@resultado.Centro</td>
                        <td>@resultado.Mesa</td>
                        <td>@resultado.EG.ToString("N0")</td>
                        <td>@resultado.NM.ToString("N0")</td>
                        <td>@resultado.LM.ToString("N0")</td>
                        <td>@resultado.JABE.ToString("N0")</td>
                        <td>@resultado.JOBR.ToString("N0")</td>
                        <td>@resultado.AE.ToString("N0")</td>
                        <td>@resultado.CF.ToString("N0")</td>
                        <td>@resultado.DC.ToString("N0")</td>
                        <td>@resultado.EM.ToString("N0")</td>
                        <td>@resultado.BERA.ToString("N0")</td>
                    </tr>
                }
            }
        </table>
        @if (@Model.Amount == 0)
        {
            <p>No hay resultados para mostrar.</p>
        }
    </div>
    <div class="pagination">
        @if (int.Parse(Model.PageNumber) > 1)
        {
            <button onclick="changePage('prev')">&lt;</button>
        }
        <span>Página @Model.PageNumber</span>
        @if (@Model.Amount > 0)
        {
            <button onclick="changePage('next')">&gt;</button>
        }
    </div>

    <!-- Votos Totales -->
    <div id="TitleContainer">
        <p>Votos Totales por Candidato:</p>
    </div>

    <table id="votosTotalesTable">
        <tr>
            <th>Edmundo Gonzalez</th>
            <th>Nicolas Maduro</th>
            <th>Luis Martinez</th>
            <th>Javier Bertucci</th>
            <th>Jose Brito</th>
            <th>Antonio Ecarri</th>
            <th>Claudio Fermin</th>
            <th>Daniel Ceballos</th>
            <th>Enrique Marquez</th>
            <th>Benjamin Rausseo</th>
        </tr>
        <tr>
            <td>@Model.SumaVotos.TotalEG.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalNM.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalLM.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalJABE.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalJOBR.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalAE.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalCF.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalDC.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalEM.ToString("N0")</td>
            <td>@Model.SumaVotos.TotalBERA.ToString("N0")</td>
        </tr>
    </table>

}

TeraFrontendMVC/Views/Shared/_SelectsPartial.cshtml
@using TeraFrontendMVC.Models.Region
@model SelectsViewModel

<!-- Select para Estados -->
<div id="selectContainer">
    <label>Estado:</label>
    <select id="selectEstado">
        <option value="">Seleccione un estado</option>
        @foreach (var estado in Model.States)
        {
            <option value="@estado.CodEdo">@estado.Nombre</option>
        }
    </select>
</div>

<!-- Select para Municipios -->
<div id="selectContainer">
    <label>Municipio:</label>
    <select id="selectMunicipio">
        <option value="">Seleccione un municipio</option>
    </select>
</div>

<!-- Select para Parroquias -->
<div id="selectContainer">
    <label>Parroquia:</label>
    <select id="selectParroquia">
        <option value="">Seleccione una parroquia</option>
    </select>
</div>